sigweb:
   #build: ./sigweb-base
   volumes:
    - $PWD/sigweb/webdev/home:/home/webdev/
    - $PWD/sigweb/httpd/logs:/var/log/apache2
    - $PWD/sigweb/httpd/html:/var/www/html
    - $PWD/sigweb/php/:/usr/local/etc/php
   expose:
    - "22"
    - "80"
    - "443"
   image: jasonodoom/sigweb-docker
   container_name: "sigweb-base"
   restart: always
mysql:
   #build: ./sigweb-mysql
   volumes:
    - $PWD/sigweb/mysql/data:/var/lib/mysql
   expose:
    - "3306"
   image: jasonodoom/sigweb-mysql
   container_name: "sigweb-db"
   restart: always
   environment:
    - MYSQL_ROOT_PASSWORD=M/$q1
    #- MYSQL_DATABASE=sigweb
pma:
  #build: ./sigweb-pma
  image: jasonodoom/sigweb-pma
  container_name: "sigweb-pma"
  restart: always
  environment:
   - PMA_ARBITRARY=1
   - PMA_USER=webdev
   - PMA_PASSWORD=mIsT3r_tumnus
 volumes:
  - /sessions

