sigweb:
   volumes:
    - $PWD/sigweb/home/webdev:/home/webdev/
   expose:
    - "22"
   image: sigweb-docker
   container_name: "sigweb-base"
apache:
   volumes:
    - $PWD/sigweb/apache/logs:/var/log/apache2
    - $PWD/sigweb/apache/html:/var/www/html
   expose:
    - "80"
   image: sigweb-apache
   container_name: "sigweb-httpd"
mysql:
   volumes:
    - $PWD/sigweb/mysql/data:/var/lib/mysql
   expose:
    - "3306"
   image: sigweb-mysql
   container_name: "sigweb-db"
