sigweb:
   #build: ./sigweb-base
   volumes:
    - $PWD/sigweb/webdev/home:/home/webdev/
   expose:
    - "22"
   image: jasonodoom/sigweb-docker
   container_name: "sigweb-base"
lap:
   #build: ./sigweb-lap
   volumes:
    - $PWD/sigweb/httpd/logs:/var/log/apache2
    - $PWD/sigweb/httpd/html:/var/www/html
    - $PWD/sigweb/php/:/usr/local/etc/php
   expose:
    - "80"
   image: jasonodoom/sigweb-lap
   container_name: "sigweb-httpd"
mysql:
   #build: ./sigweb-mysql
   volumes:
    - $PWD/sigweb/mysql/data:/var/lib/mysql
   expose:
    - "3306"
   image: jasonodoom/sigweb-mysql
   container_name: "sigweb-db"
